# basic options
theme: jekyll-theme-cayman
title: veloEnhanced
author: velolib
email: vlocitize@gmail.com
description: The official veloSMP Resource Pack

# build settings
markdown: kramdown
theme: cayman
